docs: update Rust/Python migration guide for serialization
atolab/zenoh-web pull request #71
Opened 2024-10-04 06:53 UTC by wyfo

2024-10-08 16:47 UTC, DariusIMP approved these changes
LGTM

2024-10-09 09:03 UTC, oteffahi requested changes
Some minor changes (nitpicks) for grammar and title levels.
Other than that it LGTM.

2024-10-09 09:03 UTC, oteffahi commented on content/docs/migration_1.0/Python.md
> +### Serialization
Same issue as on Rust: this is the only "sub-title", which makes the summary of the page look weird. Consider changing it.

```suggestion
## Serialization
```

2024-10-09 09:03 UTC, oteffahi commented on content/docs/migration_1.0/Python.md
> +`zenoh.ext` serialization doesn't pretend to cover every use cases, as it is just one available choice among other serialization format like JSON, Protobuf, CBOR, etc. In the end, Zenoh will just sen
```suggestion
`zenoh.ext` serialization doesn't pretend to cover all use cases, as it is just one available choice among other serialization formats like JSON, Protobuf, CBOR, etc. In the end, Zenoh will just send and receive payload raw bytes independently of the serialization used.  
```

2024-10-09 15:44 UTC, oteffahi approved these changes

2024-10-09 15:49 UTC, merged